backend:
  name: git-gateway
  repo: amir3629/Melaniejazz
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }