backend:
  name: github
  repo: amir3629/Melaniejazz
  branch: main
  auth_type: implicit
  app_id: "Ov23li5WQOVXICF1OHho"
  site_domain: "amir3629.github.io"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }